#!/bin/bash

set -e

# Resfinder
# http://cge.cbs.dtu.dk/services/data.php

DB="resfinder"

DIR=$(mktemp -d $DB.XXXXXXXX)
echo "Created temp folder: $DIR"
cd "$DIR"

echo "Downloading $DB"
curl -d 'folder=resfinder&filename=resfinder.zip&submit=resfinder.zip' https://cge.cbs.dtu.dk/cge/download_data.php > resfinder.zip

unzip resfinder.zip
rm -f all*.fsa

TITLE="Abricate Antiobiotic Resistance database (filtered ResFinder)"

cat *.fsa | \
	../../scripts/abricate-fix_resfinder_fasta - | \
	makeblastdb -out "$DB" -dbtype nucl -title "$TITLE" -logfile /dev/null -taxid 2

ls -lsa $DB.*

blastdbcmd -info -db "$DB"

echo "Results in: $DB"
