#!/bin/bash

set -e

CLEANER="./abricate-fix_resfinder_fasta"

if [ ! -x "$CLEANER" ]; then
	echo "Can't find $CLEANER - please run from within the abricate/scripts/ folder"
	exit 1
fi

# Resfinder
# http://cge.cbs.dtu.dk/services/data.php

DB="resfinder"
BLASTDB="$DB"

DIR=$(mktemp -d db.XXXXXXXX)
echo "Created temp folder: $DIR"
cd "$DIR"

echo "Getting $DB components:"
for FILE in resfinder.zip notes.txt ; do
  echo "Downloading: $FILE"
  curl -d "folder=resfinder&filename=resfinder.zip&submit=$FILE" https://cge.cbs.dtu.dk/cge/download_data.php > $FILE
done

# use -j to ensure no folders are created
unzip -j resfinder.zip
rm -f all*.fsa resfinder.zip

TITLE="Abricate Antiobiotic Resistance database (filtered ResFinder)"

cat *.fsa | \
	../$CLEANER - | \
	makeblastdb -out "$BLASTDB" -dbtype nucl -title "$TITLE" -logfile /dev/null -taxid 2

ls -lsa ${BLASTDB}.*

blastdbcmd -info -db "$BLASTDB"

echo "Results in: $DIR"

